### ISSUE TITLE
Compatible with PBS?

### ISSUE THREAD

**Issue by aidanheerdegen** [scalability-llnl/cram#1]
Sorry, I'm being lazy, and instead of reading the code ... is this compatible with PBS?

**Comment by tgamblin** [comment]
The `srun` in the example is just notional.  Cram doesn't have any integration with any particular scheduler/batch system -- you either link it into your application or `LD_PRELOAD` it.  So yes, it should work with PBS.  You should be able to pack a cram file and submit a PBS job and get it to run with your cram file.
